MVC-Models/SeminarskiTemp1/Controllers/SeminarskiController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeminarskiTemp1.EF;
using SeminarskiTemp1.EntityModels;
using SeminarskiTemp1.Models;

namespace SeminarskiTemp1.Controllers
{
    public class SeminarskiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult Prikaz(string student)
        {
            MojDBContext dBcontext = new MojDBContext();
            var studenti = dBcontext.Students.
                Where(x => student == null || x.Ime.StartsWith(student))
            .Select(x => new StudentPrikazVM.Row(x)).ToList();

            StudentPrikazVM m = new StudentPrikazVM();
            m.studenti = studenti;
            m.q = student;
            return View(m);
        }


        public ActionResult Uredi(int StudentID)
        {
            MojDBContext mojDBcontext = new MojDBContext();
            List<SelectListItem> opstine = mojDBcontext.Opstinas.Select(a => new SelectListItem
            {

                Text = a.Naziv,
                Value = a.ID.ToString()
            }).ToList();
            List<SelectListItem> fakulteti = mojDBcontext.Fakultets.Select(a => new SelectListItem
            {
                Text = a.Naziv,
                Value = a.ID.ToString()
            }).ToList();


            StudentDodajVM studenti = StudentID == 0 ? new StudentDodajVM() : mojDBcontext.Students.Where(a => StudentID == a.ID).
                Select(a => new StudentDodajVM
                {

                    ID = a.ID,
                    Ime = a.Ime,
                    Prezime = a.Prezime,
                    OpstinaID = a.OpstinaID,
                    FakultetID = a.FakultetID,
                    BrojIndeksa = a.BrojIndeksa,
                    Datum = Convert.ToDateTime(a.DatumRodjenja)
                }).Single();
            studenti.Opstine = opstine;
            studenti.Fakulteti = fakulteti;
            return View(studenti);
        }

        public ActionResult Snimi(StudentDodajVM admir)
        {
            MojDBContext dbContext = new MojDBContext();
            Student student;
            if (admir.ID == 0)
            {
                student = new Student();
                dbContext.Add(student);
                TempData["Ime"] = "Uspjesno ste dodali studenta " + admir.Ime;
            }
            else
            {
                student = dbContext.Students.Find(admir.ID);
                TempData["Ime"] = "Uspjesno ste UREDILI studenta " + admir.Ime;

            }
            student.Ime = admir.Ime;
            student.Prezime = admir.Prezime;
            student.OpstinaID = admir.OpstinaID;
            student.FakultetID = admir.FakultetID;
            student.BrojIndeksa = admir.BrojIndeksa;
            student.DatumRodjenja = admir.Datum.ToString();

            dbContext.SaveChanges();
            return Redirect(url: "/Seminarski/Poruka");
        }
        public ActionResult Detalji(int student)
        {
            MojDBContext mojDBcontext = new MojDBContext();

            StudentDetaljiVM studenti = mojDBcontext.Students.Where(a => student == a.ID).
                Select(x => new StudentDetaljiVM
                {
                    ID = x.ID,
                    Ime = x.Ime,
                    Prezime = x.Prezime,
                    DatumRodjenja = x.DatumRodjenja,
                    Opstina = x.Opstina.Naziv,
                    Fakultet = x.Fakultet.Naziv,
                    BrojIndeksa = x.BrojIndeksa

                }).Single();
            

            return View(studenti);
        }
        public IActionResult UrediStanovanje(int StanovanjeID)
        {
            MojDBContext dBContext = new MojDBContext();
            List<SelectListItem> sobe = dBContext.Sobas.Select(a => new SelectListItem
            {
                Text = a.BrojSobe.ToString(),
                Value = a.ID.ToString()
            }).ToList();
            StanovanjeUrediVM m = dBContext.Stanovanjes.Where(a => StanovanjeID == a.ID).Select(a => new StanovanjeUrediVM
            {

                ID = a.ID,
                ImePrezime = a.student.Ime + ' ' + a.student.Prezime,
                StudentID=a.student.ID,
                SobaID=a.sobaID,
                AkademskaGodina=a.AkademskaGodina

            }).Single();
            m.sobe = sobe;


            return View(m);
        }
        public IActionResult Stanovanje(int StudentID)
        {
            MojDBContext dBContext = new MojDBContext();
          
            StudentStanovanjeVM student = dBContext.Stanovanjes.Where(a => a.studentID == StudentID).Select(x => new StudentStanovanjeVM
            {
                ID=x.ID,
                ImeStudenta=x.student.Ime+" "+x.student.Prezime,
                BrojSobe = x.soba.BrojSobe,
                AkademskaGodina = x.AkademskaGodina
            }).Single();
            var studenti = dBContext.Stanovanjes.Where(a=>student.BrojSobe==a.soba.BrojSobe && a.student.ID!=StudentID).Select(x => new StudentStanovanjeVM.Row
            {
                Imecimera = x.student.Ime +" "+ x.student.Prezime+" "
            }).ToList();
            student.cimeri = studenti;
            return View(student);
        }
        public IActionResult SnimiStanovanje(StanovanjeUrediVM admir)
        {
            MojDBContext dBContext = new MojDBContext();
            Stanovanje stanovanje = new Stanovanje();
            stanovanje = dBContext.Stanovanjes.Find(admir.ID);
            stanovanje.sobaID = admir.SobaID;
            dBContext.SaveChanges();
            return Redirect(url: "/Seminarski/Prikaz");
        }

        public ActionResult Obrisi(int ID)
        {

            MojDBContext dBcontext = new MojDBContext();

            Student student = dBcontext.Students.Find(ID);
            dBcontext.Remove(student);
            dBcontext.SaveChanges();
            TempData["Ime"] = "Uspjesno ste Obrisali studenta " + student.Ime;
            return Redirect(url: "/Seminarski/Poruka");
        }
        public ActionResult Poruka()
        {
            StanovanjeDodajVM m = new StanovanjeDodajVM();
            return View(m);
        }

        public IActionResult DodajStanovanje()
        {
            return View();
        }
    }
}

MVC-Models/SeminarskiTemp1/Views/Seminarski/Detalji.cshtml
@{
    //var student = (SeminarskiTemp1.EntityModels.Student)ViewData["student"];
    //var opstina = (List<SeminarskiTemp1.EntityModels.Opstina>)ViewData["opstine"];
    //var fakulteti = (List<SeminarskiTemp1.EntityModels.Fakultet>)ViewData["fakulteti"];

    string[] niz = { "Ime", "Prezime", "DatumRodjenja", "Opstina", "Fakultet", "BrojIndeksa" };
    Layout = null;
}
@model StudentDetaljiVM
<style>


    .klasa {
        border: 1px solid black;
    }

        .klasa input, select {
            margin: 2px 10px 10px 0px;
            width: 400px;
            padding: 5px;
            border: none;
        }

    .klasa div{
        margin-left:10px
    }
</style>
<div class="klasa">
    <div>
        <h4 class="text-success">Detalji studenta</h4>
    </div>
    <div>
        <label>Ime : </label>
        <input asp-for="Ime" readonly />
    </div>

    <div>
        <label>Prezime : </label>
        <input asp-for="Prezime" readonly />
    </div>
    <div>
        <label>Datum Rodjenja : </label>
        <input asp-for="DatumRodjenja" readonly />
    </div>
    <div>

        <label>Opstina : </label>
        <input asp-for="Opstina" readonly />



    </div>
    <div>
        <label>Fakultet : </label>
        <input asp-for="Fakultet" readonly />
    </div>

    <div>

        <label>Broj Indeksa : </label>
        <input asp-for="BrojIndeksa" readonly />

    </div>
</div>

MVC-Models/SeminarskiTemp1/Views/Seminarski/DodajStanovanje.cshtml
@model StanovanjeDodajVM
@{
    Layout = null;
}
<style>
    .forma {
        border: 2px solid lightgray;
        border-radius: 5px;
        
        padding: 50px;
        padding-left: 0px
    }
   .forma input{
        padding:10px;
        border-radius:10px;
 
    }
   .forma select{
       padding:10px;
        border-radius:10px;
        margin-right:30px

   }
 
   .forma label{
       padding:5px
   }
</style>

    <form  asp-action="SnimiStanovanje" asp-controller="Seminarski">
     
            <input asp-for="ID" style="display:none" />
            @*<div class="form-group">
                <label>Studenti</label>
                <select asp-for="StudentID" asp-items="@Model.studenti" />
            </div>
            <div class="form-group">
                <label>Sobe</label>
                <select asp-for="sobe" asp-items="@Model.sobe" />
            </div>*@

            <div  class="form-group">
                <label> Akademska godina</label>
                <input asp-for="AkademskaGodina"  class="form-control"/>
            </div>




            <input type="submit" value="Submit" class="btn btn-danger" />
    
    </form>

MVC-Models/SeminarskiTemp1/Views/Seminarski/Poruka.cshtml
@{
    var ime = TempData["Ime"];
}

<span>@ime</span>
<a href="/Seminarski/Prikaz">BACK</a>

MVC-Models/SeminarskiTemp1/Views/Seminarski/Prikaz.cshtml
<style type="text/css">
    #mojID {
        padding: 5px;
        margin: 5px 5px 5px 0px;
        width: 200px;
        border-radius:10px;
    }

    form {
        float: left;
    }

    #buton {
        float: right;
        margin: 5px;
    }

    span {
        cursor: pointer
    }
   
    }
</style>
<body>
    @{

        @model StudentPrikazVM
    }
    <form>

        <input name="student" id="mojID" value="@Model.q" placeholder="Trazi"/>
        <input type="submit" value="Trazi" class="btn btn-dark" />

    </form>
    <button type="button" id="buton" class="btn btn-dark" onclick="window.location='/Seminarski/Uredi'">Dodaj Studenta</button>
    <button type="button" id="buton" class="btn btn-dark" onclick="window.location='/Soba/Prikazi'">Sobe</button>
    <button type="button" id="buton" class="btn btn-dark" onclick="window.location='/Seminarski/DodajStanovanje'">Useljavanje</button>
    <table class="table">
        <thead class="thead">
            <tr>
                <th>Ime i prezime</th>


            </tr>
        </thead>
        @foreach (StudentPrikazVM.Row item in Model.studenti)
        {
            <tr>
                <td>@item.Ime @item.Prezime</td>
                <th style="color:blue;"><span onclick=PrikaziStudenta(@item.ID) class="btn btn-info">Detalji</span></th>
                <th style="color:red">  <span onclick="window.location='/Seminarski/Obrisi?ID='+@item.ID" class="btn btn-danger">Obrisi</span></th>
                <th style="color:yellow">  <span onclick="window.location='/Seminarski/Uredi?StudentID='+@item.ID" class="btn btn-primary">Uredi</span></th>


            </tr>


        }
    </table>

    <div id="ajaxTabela">

    </div>


</body>
<script>

    function PrikaziStudenta(StudentID) {

        var url = "/Seminarski/StanovanJe?StudentID=" + StudentID;
        var zahtjev = new XMLHttpRequest();
        zahtjev.onload = function () {
            if (zahtjev.status === 200) {
                document.getElementById("ajaxTabela").innerHTML = zahtjev.responseText;
            } else {

            }
        };
        zahtjev.open("GET", url, true);
        zahtjev.send();

    }

    function UrediStanovanje(StanovanjeID) {
        var url = "/Seminarski/UrediStanovanje?StanovanjeID=" + StanovanjeID;
        $.get(url, function (d) {
            $("#ajaxTabela").html(d);
        });
    }
</script>

MVC-Models/SeminarskiTemp1/Views/Seminarski/Stanovanje.cshtml
@model StudentStanovanjeVM
@{
    Layout = null;

}

<table class="table">
    <thead>
        <tr>
            <th>Ime Studenta</th>
            <th>Broj Sobe</th>
            <th>Akademska godina</th>
            <th>Cimeri</th>
            <th>Uredi</th>

        </tr>
    </thead>
    <tr>
        <th>@Model.ImeStudenta</th>
        <th>@Model.BrojSobe</th>
        <th>@Model.AkademskaGodina</th>
        <th>
            @{
                foreach (var item in Model.cimeri)
                {
                    @item.Imecimera<br />
                }
            }
        </th>
        <th><button class="btn btn-primary" onclick=UrediStanovanje(@Model.ID)>Uredi</button></th>
    </tr>

</table>

MVC-Models/SeminarskiTemp1/Views/Seminarski/Uredi.cshtml
<h3 class="text-success">Dodavanje novog studenta</h3>
@{



}
@model StudentDodajVM
<style>
    form input, select {
        margin: 2px 10px 10px 0px;
        width: 200px;
        padding: 5px;
    }
</style>
<form asp-action="Snimi" method="post">
    <div style="display:none">
        <label></label><br />
        <input asp-for="ID" />
    </div>
    <div>
        <label>Ime</label><br />
        <input asp-for="Ime" />
    </div>

    <div>
        <label>Prezime</label><br />
        <input asp-for="Prezime" />
    </div>
    <div>
        <label>Datum Rodjenja</label><br />
        <input asp-for="Datum" type="date" />
    </div>
    <div>
        <label>Opstina</label><br />
        <select asp-for="OpstinaID" asp-items="@Model.Opstine">
        </select>

    </div>
    <div>
        <label>Fakultet</label><br />
        <select asp-for="FakultetID" asp-items="@Model.Fakulteti">
        </select>
    </div>
    <div>
        <label>Broj Indeksa</label><br />
        <input asp-for="BrojIndeksa" />
    </div>
    <input type="submit" name="Snimi" value="Sacuvaj" class="btn-success" />
</form>

MVC-Models/SeminarskiTemp1/Views/Seminarski/UrediStanovanje.cshtml
@model StanovanjeUrediVM
@{
    Layout = null;
}
<style>
    .forma {
        border: 2px solid lightgray;
        border-radius: 5px;
        
        padding: 50px;
        padding-left: 0px
    }
   .forma input{
        padding:10px;
        border-radius:10px;
 
    }
   .forma select{
       padding:10px;
        border-radius:10px;
        margin-right:30px

   }
 
   .forma label{
       padding:5px
   }
</style>

    <form class="forma" asp-action="SnimiStanovanje" asp-controller="Seminarski">
     
            <input asp-for="ID" style="display:none" />
            <input asp-for="StudentID" style="display:none" />

            <label>Ime i Prezime</label>
            <input asp-for="ImePrezime" disabled  style="background-color:white"/>

            <label> Akademska godina</label>
            <input asp-for="AkademskaGodina" disabled  style="background-color:white"/>

            <label> Broj Sobe</label>
            <select asp-for="SobaID" asp-items="@Model.sobe" style="width:150px">
            </select>



            <input type="submit" value="Submit" class="btn btn-danger" />
    
    </form>